language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t trang/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true trang/docker-react npm run test
